import Foundation

enum SmartStegoData {
    struct Grammar {
        let openers: [String]
        let openerKind: [Int]
        let structOf: [Int]
        let structures: [[String]]
        let slots: [[String]]
    }

    static let english = Grammar(
        openers: ["the", "my", "our", "his", "her", "its", "their", "that", "this", "your", "one", "each", "every", "some", "another", "either", "honestly", "frankly", "clearly", "surely", "truly", "sadly", "oddly", "luckily", "apparently", "seemingly", "generally", "obviously", "certainly", "perhaps", "admittedly", "curiously", "notably", "presumably", "arguably", "evidently", "naturally", "interestingly", "indeed", "supposedly", "now", "then", "later", "soon", "still", "today", "often", "lately", "once", "again", "meanwhile", "afterward", "recently", "suddenly", "nowadays", "shortly", "eventually", "initially", "previously", "sometimes", "nearby", "thereafter", "henceforth", "elsewhere"],
        openerKind: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        structOf: [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0],
        structures: [["#0", "#1", "#3", "#0", "#2"], ["#0", "#1", "#3", "#0", "#2", "#4"], ["#0", "#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"], ["#1", "#3", "#0", "#2"], ["#1", "#3", "#0", "#2", "#4"], ["#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"]],
        slots: [
            [
                "the", "my", "our", "his", "her", "its", "their", "that",
                "this", "your", "one", "each", "every", "some", "another", "either",
            ],
            [
                "manager", "brother", "sister", "neighbor", "driver", "teacher", "doctor", "waiter",
                "officer", "farmer", "painter", "builder", "banker", "lawyer", "dancer", "singer",
                "writer", "player", "soldier", "sailor", "hunter", "keeper", "worker", "printer",
                "plumber", "tailor", "jeweler", "baker", "butcher", "barber", "porter", "cleaner",
                "gardener", "guardian", "captain", "colonel", "curator", "senator", "warden", "tenant",
                "patron", "cousin", "nephew", "uncle", "father", "husband", "partner", "stranger",
                "visitor", "customer", "founder", "speaker", "trainer", "drummer", "actor", "editor",
                "author", "sponsor", "rival", "guest", "clerk", "pilot", "nurse", "mayor",
                "judge", "guard", "agent", "cook", "coach", "scout", "mentor", "broker",
                "dealer", "trader", "miner", "welder", "mason", "roofer", "potter", "weaver",
                "brewer", "sculptor", "architect", "engineer", "scientist", "professor", "student", "scholar",
                "tutor", "lecturer", "principal", "librarian", "cashier", "accountant", "auditor", "courier",
                "messenger", "fisherman", "shepherd", "rancher", "logger", "carpenter", "electrician", "mechanic",
                "machinist", "blacksmith", "locksmith", "cobbler", "decorator", "plasterer", "surgeon", "dentist",
                "chemist", "florist", "grocer", "jailer", "ranger", "sheriff", "deputy", "constable",
                "detective", "inspector", "watchman", "gatekeeper", "butler", "envoy", "tycoon", "warrior",
            ],
            [
                "box", "letter", "window", "door", "table", "chair", "ladder", "basket",
                "bottle", "candle", "mirror", "pencil", "ticket", "wallet", "jacket", "blanket",
                "pillow", "kettle", "teapot", "saucer", "hammer", "anchor", "camera", "drawer",
                "cabinet", "package", "parcel", "folder", "ribbon", "button", "pocket", "collar",
                "barrel", "bucket", "shovel", "lantern", "compass", "marble", "napkin", "crayon",
                "marker", "sponge", "trophy", "magnet", "banner", "cushion", "whistle", "wrench",
                "needle", "thread", "envelope", "notebook", "umbrella", "suitcase", "backpack", "toolbox",
                "flashlight", "keyboard", "monitor", "charger", "bracelet", "necklace", "sandal", "slipper",
                "glove", "scarf", "helmet", "apron", "towel", "curtain", "carpet", "mattress",
                "pitcher", "goblet", "platter", "tumbler", "spatula", "ladle", "funnel", "grater",
                "skillet", "cauldron", "thimble", "spindle", "chisel", "handle", "mallet", "hatchet",
                "sickle", "rake", "trowel", "nozzle", "hinge", "bracket", "clamp", "lever",
                "pulley", "gasket", "valve", "piston", "stapler", "binder", "ledger", "receipt",
                "clipboard", "notepad", "calendar", "poster", "album", "canvas", "easel", "palette",
                "brush", "stencil", "ruler", "protractor", "eraser", "satchel", "pouch", "crate",
                "carton", "hamper", "tray", "jug", "flask", "canteen", "cork", "gavel",
                "lid", "spoon", "fork", "knife", "plate", "bowl", "mug", "cup",
                "dish", "saucepan", "whisk", "sieve", "colander", "corkscrew", "peeler", "masher",
                "hook", "strainer", "decanter", "carafe", "chalice", "tankard", "flagon", "comb",
                "razor", "loofah", "book", "novel", "diary", "atlas", "manual", "booklet",
                "leaflet", "pamphlet", "magazine", "brochure", "map", "blueprint", "sketch", "drawing",
                "portrait", "painting", "postcard", "stamp", "coin", "token", "medal", "badge",
                "brooch", "pendant", "locket", "earring", "cufflink", "watch", "clock", "timer",
                "dial", "gauge", "meter", "sensor", "switch", "socket", "plug", "cord",
                "rope", "chain", "strap", "buckle", "zipper", "clasp", "nail", "screw",
                "rivet", "washer", "spring", "ratchet", "spanner", "crowbar", "pickaxe", "saw",
                "drill", "sander", "vise", "brick", "tile", "plank", "board", "beam",
                "dowel", "wedge", "grommet", "pot", "vase", "urn", "planter", "basin",
                "tub", "pail", "jar", "tin", "keg", "drum", "canister", "cylinder",
                "tube", "pipe", "hose", "spout", "paddle", "oar", "broom", "mop",
                "duster", "rag", "cloth", "spade", "hoe", "scythe", "cleaver", "grinder",
                "blender", "toaster", "beaker", "vial", "syringe", "knob", "peg", "latch",
            ],
            [
                "found", "left", "moved", "changed", "opened", "closed", "fixed", "carried",
                "noticed", "painted", "cleaned", "counted", "watched", "pushed", "pulled", "lifted",
                "dropped", "grabbed", "tossed", "folded", "packed", "mailed", "signed", "marked",
                "traced", "sketched", "polished", "guarded", "buried", "planted", "sorted", "stacked",
                "labeled", "wrapped", "tied", "locked", "hid", "sold", "bought", "borrowed",
                "returned", "repaired", "trimmed", "brushed", "rinsed", "dusted", "framed", "hauled",
                "stored", "fetched", "delivered", "gathered", "inspected", "kept", "held", "placed",
                "turned", "showed", "brought", "chose", "used", "offered", "described", "mentioned",
                "remembered", "examined", "praised", "wanted", "needed", "checked", "grasped", "hoisted",
                "shifted", "nudged", "hurled", "flung", "stashed", "hoarded", "collected", "assembled",
                "measured", "weighed", "numbered", "tagged", "stamped", "sealed", "bundled", "loaded",
                "unloaded", "shipped", "handled", "touched", "tested", "rated", "ranked", "reviewed",
                "studied", "drafted", "copied", "printed", "scanned", "filed", "logged", "listed",
                "named", "claimed", "seized", "snatched", "retrieved", "recovered", "obtained", "secured",
                "acquired", "adopted", "selected", "picked", "sampled", "favored", "preferred", "scrubbed",
                "wiped", "mopped", "swept", "raked", "shoveled", "dug", "cleared", "spotted",
                "took", "gave", "sent", "threw", "caught", "kicked", "rolled", "slid",
                "dragged", "shoved", "twisted", "bent", "snapped", "split", "tore", "cut",
                "carved", "drilled", "sawed", "nailed", "screwed", "bolted", "glued", "taped",
                "pinned", "clipped", "strapped", "buckled", "zipped", "hung", "mounted", "propped",
                "leaned", "balanced", "steadied", "gripped", "clutched", "clenched", "squeezed", "pressed",
                "poked", "prodded", "tapped", "rubbed", "scraped", "scratched", "sanded", "buffed",
                "waxed", "oiled", "greased", "coated", "primed", "sprayed", "dipped", "soaked",
                "drained", "emptied", "filled", "poured", "hefted", "jostled", "shuffled", "rearranged",
                "reordered", "compressed", "unwrapped", "scoured", "whittled", "notched", "cleaved", "stripped",
                "prised", "hollowed", "cracked", "crushed", "ground", "pounded", "hammered", "flattened",
                "smoothed", "leveled", "aligned", "adjusted", "tuned", "wired", "soldered", "welded",
                "riveted", "patched", "mended", "stitched", "sewed", "coiled", "knotted", "laced",
                "threaded", "strung", "hooked", "latched", "fastened", "clasped", "clamped", "wedged",
                "jammed", "lodged", "inserted", "extracted", "removed", "replaced", "swapped", "rotated",
                "flipped", "inverted", "reversed", "tilted", "angled", "lugged", "toted", "shouldered",
                "yanked", "tugged", "heaved", "trundled", "wheeled", "carted", "ferried", "conveyed",
            ],
            [
                "quietly", "quickly", "slowly", "calmly", "gladly", "boldly", "neatly", "firmly",
                "gently", "roughly", "warmly", "carefully", "suddenly", "eagerly", "happily", "proudly",
                "kindly", "politely", "bravely", "wisely", "softly", "loudly", "sternly", "sharply",
                "smoothly", "swiftly", "tightly", "loosely", "plainly", "freely", "briskly", "promptly",
                "silently", "patiently", "coolly", "keenly", "deftly", "nimbly", "steadily", "bluntly",
                "crisply", "fondly", "warily", "meekly", "gruffly", "tidily", "snugly", "evenly",
                "squarely", "grimly", "sagely", "aptly", "curtly", "tersely", "dryly", "wryly",
                "primly", "tautly", "lithely", "brightly", "stoutly", "gamely", "blithely", "jauntily",
            ],
            [
                "and", "but", "so", "yet", "then", "while", "because", "though",
            ],
        ])

    static let russian = Grammar(
        openers: ["мой", "наш", "его", "твой", "ваш", "их", "тот", "этот", "один", "каждый", "любой", "другой", "такой", "некий", "иной", "всякий", "конечно", "наверное", "впрочем", "однако", "кажется", "видимо", "пожалуй", "возможно", "кстати", "значит", "похоже", "вероятно", "очевидно", "честно", "откровенно", "безусловно", "разумеется", "действительно", "признаться", "словом", "короче", "наоборот", "напротив", "следовательно", "вчера", "сегодня", "скоро", "тогда", "часто", "снова", "опять", "потом", "сразу", "теперь", "сначала", "позже", "наконец", "вдруг", "порой", "нынче", "недавно", "вскоре", "иногда", "обычно", "изредка", "давно", "всегда", "ныне"],
        openerKind: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        structOf: [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0],
        structures: [["#0", "#1", "#3", "#0", "#2"], ["#0", "#1", "#3", "#0", "#2", "#4"], ["#0", "#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"], ["#1", "#3", "#0", "#2"], ["#1", "#3", "#0", "#2", "#4"], ["#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"]],
        slots: [
            [
                "мой", "наш", "его", "твой", "ваш", "их", "тот", "этот",
                "один", "каждый", "любой", "другой", "такой", "некий", "иной", "всякий",
            ],
            [
                "брат", "сосед", "директор", "водитель", "учитель", "доктор", "повар", "сторож",
                "механик", "гость", "начальник", "охранник", "курьер", "продавец", "парень", "сын",
                "отец", "друг", "дядя", "внук", "племянник", "кузнец", "пекарь", "портной",
                "сапожник", "столяр", "маляр", "слесарь", "электрик", "плотник", "каменщик", "пастух",
                "рыбак", "охотник", "солдат", "матрос", "капитан", "полковник", "генерал", "министр",
                "депутат", "адвокат", "банкир", "кассир", "бухгалтер", "инженер", "писатель", "художник",
                "музыкант", "певец", "танцор", "садовник", "дворник", "ученик", "студент", "профессор",
                "архитектор", "пилот", "шофер", "токарь", "сварщик", "кровельщик", "тренер", "вратарь",
                "дедушка", "прадед", "тесть", "шурин", "крестник", "наследник", "жених", "вдовец",
                "писарь", "лекарь", "знахарь", "пахарь", "звонарь", "рыцарь", "воин", "стрелок",
                "разведчик", "моряк", "боцман", "штурман", "лоцман", "юнга", "атаман", "старшина",
                "сержант", "майор", "адмирал", "маршал", "комендант", "конвоир", "тюремщик", "палач",
                "гонец", "посол", "наместник", "барин", "помещик", "купец", "лавочник", "торговец",
                "ростовщик", "счетовод", "писец", "толмач", "аптекарь", "трубач", "барабанщик", "скрипач",
                "гусляр", "плясун", "весельчак", "силач", "богатырь", "удалец", "молодец", "храбрец",
                "мудрец", "гордец", "хитрец", "беглец", "гребец", "борец", "пловец", "чтец",
            ],
            [
                "ключ", "стол", "дом", "документ", "план", "ответ", "вопрос", "шкаф",
                "ящик", "конверт", "чемодан", "забор", "мешок", "телефон", "ноутбук", "паспорт",
                "билет", "журнал", "словарь", "стул", "диван", "замок", "молоток", "топор",
                "гвоздь", "болт", "винт", "провод", "кабель", "фонарь", "зонт", "портфель",
                "рюкзак", "пакет", "сундук", "ларец", "сейф", "компас", "бинокль", "микроскоп",
                "прибор", "аппарат", "мотор", "двигатель", "насос", "вентилятор", "холодильник", "чайник",
                "стакан", "кувшин", "горшок", "самовар", "поднос", "дуршлаг", "совок", "веник",
                "ковш", "таз", "бидон", "термос", "графин", "сосуд", "пенал", "брусок",
                "стержень", "карандаш", "маркер", "циркуль", "транспортир", "ластик", "блокнот", "дневник",
                "альбом", "плакат", "свиток", "жетон", "бумажник", "ремень", "галстук", "шарф",
                "платок", "башмак", "сапог", "ботинок", "валенок", "тапок", "носок", "халат",
                "пиджак", "свитер", "картуз", "колпак", "шлем", "щит", "меч", "кинжал",
                "клинок", "штык", "арбалет", "самокат", "велосипед", "мопед", "прицеп", "якорь",
                "штурвал", "руль", "поршень", "клапан", "рычаг", "маховик", "подшипник", "шуруп",
                "дюбель", "шпунт", "обруч", "бочонок", "черпак", "половник", "противень", "чугунок",
                "котелок", "ухват", "рубанок", "напильник", "резец", "зубец", "крючок", "лоскут",
            ],
            [
                "взял", "отдал", "продал", "купил", "закрыл", "открыл", "оставил", "забрал",
                "вернул", "спрятал", "достал", "убрал", "поднял", "опустил", "сломал", "помыл",
                "вымыл", "покрасил", "подписал", "сложил", "порвал", "склеил", "собрал", "разобрал",
                "проверил", "заметил", "потерял", "получил", "отправил", "поймал", "бросил", "кинул",
                "схватил", "толкнул", "подвинул", "завязал", "развязал", "запер", "погрузил", "наполнил",
                "измерил", "взвесил", "посчитал", "пересчитал", "отметил", "пометил", "завернул", "распаковал",
                "упаковал", "нарисовал", "вычистил", "почистил", "отмыл", "разбил", "починил", "настроил",
                "передвинул", "припрятал", "стащил", "утащил", "сдвинул", "приподнял", "подобрал", "выбрал",
                "показал", "держал", "хранил", "поставил", "повернул", "предложил", "описал", "упомянул",
                "запомнил", "осмотрел", "похвалил", "испытал", "оценил", "изучил", "скопировал", "начертил",
                "напечатал", "переставил", "заполнил", "опечатал", "обвязал", "связал", "перевязал", "подвязал",
                "прицепил", "зацепил", "отцепил", "приклеил", "прибил", "привинтил", "прикрутил", "отвинтил",
                "открутил", "заклепал", "запаял", "спаял", "залудил", "смахнул", "стряхнул", "обмахнул",
                "расчистил", "намотал", "размотал", "смотал", "перемотал", "закатал", "раскатал", "свернул",
                "прижал", "отложил", "ощупал", "придвинул", "отодвинул", "пододвинул", "схоронил", "припас",
                "нащупал", "нашарил", "ухватил", "стиснул", "сжал", "разжал", "катнул", "пихнул",
                "подхватил", "перехватил", "обхватил", "захватил", "отхватил", "взвалил", "свалил", "навалил",
                "скатил", "закатил", "выкатил", "вкатил", "подкатил", "откатил", "натянул", "подтянул",
                "затянул", "оттянул", "вытянул", "протянул", "растянул", "стянул", "воткнул", "заткнул",
                "привязал", "отвязал", "навязал", "увязал", "скрепил", "укрепил", "закрепил", "прикрепил",
                "открепил", "подпилил", "отпилил", "распилил", "спилил", "просверлил", "высверлил", "пробил",
                "забил", "вбил", "подбил", "отбил", "сбил", "приколотил", "заколотил", "сколотил",
                "подклеил", "заклеил", "расклеил", "переклеил", "обклеил", "завинтил", "подвинтил", "свинтил",
                "разложил", "переложил", "подложил", "заложил", "выложил", "наложил", "уложил", "подцепил",
                "нацепил", "сцепил", "расцепил", "примерил", "отмерил", "вымерил", "замерил", "подсчитал",
                "насчитал", "отсчитал", "просчитал", "подровнял", "разровнял", "заровнял", "подчистил", "перечистил",
                "надраил", "отдраил", "продраил", "приладил", "наладил", "приспособил", "примотал", "подмотал",
                "обмотал", "замотал", "подкрутил", "накрутил", "закрутил", "перекрутил", "скрутил", "раскрутил",
                "подсунул", "засунул", "всунул", "высунул", "просунул", "рассовал", "распихал", "затолкал",
                "протолкал", "запихал", "впихнул", "отпихнул", "распрямил", "выпрямил", "погнул", "согнул",
                "разогнул", "перегнул", "надломил", "разломил", "переломил", "отломил", "подломил", "заломил",
                "наклеил", "вклеил", "отклеил", "вставил", "выставил", "приставил", "подставил", "выдвинул",
            ],
            [
                "тихо", "быстро", "медленно", "спокойно", "охотно", "смело", "аккуратно", "крепко",
                "бережно", "грубо", "тепло", "осторожно", "внезапно", "радостно", "гордо", "вежливо",
                "храбро", "мудро", "мягко", "громко", "строго", "резко", "плавно", "ловко",
                "молча", "нарочно", "случайно", "дважды", "вместе", "отдельно", "рано", "поздно",
                "вчера", "утром", "ночью", "поутру", "недавно", "немедленно", "поспешно", "терпеливо",
                "ровно", "прямо", "косо", "бойко", "шустро", "цепко", "живо", "чинно",
                "смирно", "робко", "дерзко", "угрюмо", "хмуро", "весело", "бодро", "вяло",
                "тускло", "скупо", "щедро", "редко", "густо", "спешно", "тщательно", "ретиво",
            ],
            [
                "и", "но", "а", "затем", "потом", "пока", "когда", "поэтому",
            ],
        ])

}
