package com.kryptos.android.core

internal object SmartStegoData {
    class Grammar(
        val openers: List<String>,
        val openerKind: List<Int>,
        val structOf: List<Int>,
        val structures: List<List<String>>,
        val slots: List<List<String>>,
    )

    val english = Grammar(
        openers = listOf("the", "my", "our", "his", "her", "its", "their", "that", "this", "your", "one", "each", "every", "some", "another", "either", "honestly", "frankly", "clearly", "surely", "truly", "sadly", "oddly", "luckily", "apparently", "seemingly", "generally", "obviously", "certainly", "perhaps", "admittedly", "curiously", "notably", "presumably", "arguably", "evidently", "naturally", "interestingly", "indeed", "supposedly", "now", "then", "later", "soon", "still", "today", "often", "lately", "once", "again", "meanwhile", "afterward", "recently", "suddenly", "nowadays", "shortly", "eventually", "initially", "previously", "sometimes", "nearby", "thereafter", "henceforth", "elsewhere"),
        openerKind = listOf(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
        structOf = listOf(3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0),
        structures = listOf(listOf("#0", "#1", "#3", "#0", "#2"), listOf("#0", "#1", "#3", "#0", "#2", "#4"), listOf("#0", "#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2", "#4"), listOf("#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2")),
        slots = listOf(
            listOf(
                "the", "my", "our", "his", "her", "its", "their", "that",
                "this", "your", "one", "each", "every", "some", "another", "either",
            ),
            listOf(
                "manager", "brother", "sister", "neighbor", "driver", "teacher", "doctor", "waiter",
                "officer", "farmer", "painter", "builder", "banker", "lawyer", "dancer", "singer",
                "writer", "player", "surveyor", "sailor", "hunter", "keeper", "worker", "printer",
                "plumber", "tailor", "jeweler", "baker", "butcher", "barber", "porter", "cleaner",
                "gardener", "guardian", "captain", "colonel", "curator", "senator", "warden", "tenant",
                "patron", "cousin", "nephew", "uncle", "father", "husband", "partner", "stranger",
                "visitor", "customer", "founder", "speaker", "trainer", "drummer", "actor", "editor",
                "author", "sponsor", "rival", "guest", "clerk", "pilot", "nurse", "mayor",
                "judge", "guard", "agent", "cook", "coach", "scout", "mentor", "broker",
                "conductor", "trader", "miner", "welder", "mason", "roofer", "potter", "weaver",
                "brewer", "sculptor", "architect", "engineer", "scientist", "professor", "student", "scholar",
                "tutor", "lecturer", "principal", "librarian", "cashier", "accountant", "auditor", "courier",
                "messenger", "fisherman", "shepherd", "rancher", "logger", "carpenter", "electrician", "mechanic",
                "machinist", "blacksmith", "locksmith", "cobbler", "decorator", "plasterer", "surgeon", "dentist",
                "chemist", "florist", "grocer", "jailer", "ranger", "sheriff", "deputy", "constable",
                "detective", "inspector", "watchman", "gatekeeper", "butler", "envoy", "tycoon", "notary",
            ),
            listOf(
                "box", "letter", "window", "door", "table", "chair", "ladder", "basket",
                "bottle", "candle", "mirror", "pencil", "ticket", "wallet", "jacket", "blanket",
                "pillow", "kettle", "teapot", "saucer", "hammer", "anchor", "camera", "drawer",
                "cabinet", "package", "parcel", "folder", "ribbon", "button", "pocket", "collar",
                "barrel", "bucket", "shovel", "lantern", "compass", "marble", "napkin", "crayon",
                "marker", "sponge", "trophy", "magnet", "banner", "cushion", "whistle", "wrench",
                "needle", "thread", "envelope", "notebook", "umbrella", "suitcase", "backpack", "toolbox",
                "flashlight", "keyboard", "monitor", "charger", "bracelet", "necklace", "sandal", "slipper",
                "glove", "scarf", "helmet", "apron", "towel", "curtain", "carpet", "mattress",
                "pitcher", "goblet", "platter", "tumbler", "spatula", "ladle", "funnel", "grater",
                "skillet", "cauldron", "thimble", "spindle", "chisel", "handle", "mallet", "hatchet",
                "sickle", "rake", "trowel", "nozzle", "hinge", "bracket", "clamp", "lever",
                "pulley", "gasket", "valve", "piston", "stapler", "binder", "ledger", "receipt",
                "clipboard", "notepad", "calendar", "poster", "album", "canvas", "easel", "palette",
                "brush", "stencil", "ruler", "protractor", "eraser", "satchel", "pouch", "crate",
                "carton", "hamper", "tray", "jug", "flask", "canteen", "cork", "gavel",
                "lid", "spoon", "fork", "coaster", "plate", "bowl", "mug", "cup",
                "dish", "saucepan", "whisk", "sieve", "colander", "corkscrew", "peeler", "masher",
                "hook", "strainer", "decanter", "carafe", "chalice", "tankard", "flagon", "comb",
                "razor", "loofah", "book", "novel", "diary", "atlas", "manual", "booklet",
                "leaflet", "pamphlet", "magazine", "placard", "map", "blueprint", "sketch", "drawing",
                "portrait", "painting", "postcard", "stamp", "coin", "token", "medal", "badge",
                "brooch", "pendant", "locket", "earring", "cufflink", "watch", "clock", "timer",
                "dial", "gauge", "meter", "sensor", "switch", "socket", "plug", "cord",
                "rope", "chain", "strap", "buckle", "zipper", "clasp", "nail", "screw",
                "rivet", "washer", "spring", "ratchet", "spanner", "crowbar", "pickaxe", "saw",
                "drill", "sander", "vise", "brick", "tile", "plank", "board", "beam",
                "dowel", "wedge", "grommet", "pot", "vase", "urn", "planter", "basin",
                "tub", "pail", "jar", "tin", "keg", "drum", "canister", "cylinder",
                "tube", "pipe", "hose", "spout", "paddle", "oar", "broom", "mop",
                "duster", "rag", "cloth", "spade", "hoe", "scythe", "cleaver", "grinder",
                "blender", "toaster", "beaker", "vial", "footstool", "knob", "peg", "latch",
            ),
            listOf(
                "found", "left", "moved", "changed", "opened", "closed", "fixed", "carried",
                "noticed", "painted", "cleaned", "counted", "watched", "pushed", "pulled", "lifted",
                "dropped", "grabbed", "tossed", "folded", "packed", "mailed", "signed", "marked",
                "traced", "sketched", "polished", "guarded", "buried", "planted", "sorted", "stacked",
                "labeled", "wrapped", "tied", "locked", "hid", "sold", "bought", "borrowed",
                "returned", "repaired", "trimmed", "brushed", "rinsed", "dusted", "framed", "hauled",
                "stored", "fetched", "delivered", "gathered", "inspected", "kept", "held", "placed",
                "turned", "showed", "brought", "chose", "used", "offered", "described", "mentioned",
                "remembered", "examined", "praised", "wanted", "needed", "checked", "grasped", "hoisted",
                "shifted", "nudged", "hurled", "flung", "stashed", "hoarded", "collected", "assembled",
                "measured", "weighed", "numbered", "tagged", "stamped", "sealed", "bundled", "loaded",
                "unloaded", "shipped", "handled", "touched", "tested", "rated", "ranked", "reviewed",
                "studied", "drafted", "copied", "printed", "scanned", "filed", "logged", "listed",
                "named", "claimed", "seized", "snatched", "retrieved", "recovered", "obtained", "secured",
                "acquired", "adopted", "selected", "picked", "sampled", "favored", "preferred", "scrubbed",
                "wiped", "mopped", "swept", "raked", "shoveled", "dug", "cleared", "spotted",
                "took", "gave", "sent", "threw", "caught", "kicked", "rolled", "slid",
                "dragged", "shoved", "twisted", "bent", "snapped", "split", "tore", "cut",
                "carved", "drilled", "sawed", "nailed", "screwed", "bolted", "glued", "taped",
                "pinned", "clipped", "strapped", "buckled", "zipped", "hung", "mounted", "propped",
                "leaned", "balanced", "steadied", "gripped", "clutched", "clenched", "squeezed", "pressed",
                "poked", "prodded", "tapped", "rubbed", "burnished", "scratched", "sanded", "buffed",
                "waxed", "oiled", "greased", "coated", "primed", "sprayed", "dipped", "soaked",
                "drained", "emptied", "filled", "poured", "hefted", "jostled", "shuffled", "rearranged",
                "reordered", "compressed", "unwrapped", "scoured", "whittled", "notched", "cleaved", "stripped",
                "prised", "hollowed", "cracked", "crushed", "ground", "pounded", "hammered", "flattened",
                "smoothed", "leveled", "aligned", "adjusted", "tuned", "wired", "soldered", "welded",
                "riveted", "patched", "mended", "stitched", "sewed", "coiled", "knotted", "laced",
                "threaded", "strung", "hooked", "latched", "fastened", "clasped", "clamped", "wedged",
                "jammed", "lodged", "inserted", "extracted", "removed", "replaced", "swapped", "rotated",
                "flipped", "inverted", "reversed", "tilted", "angled", "lugged", "toted", "shouldered",
                "yanked", "tugged", "heaved", "trundled", "wheeled", "carted", "ferried", "conveyed",
            ),
            listOf(
                "quietly", "quickly", "slowly", "calmly", "gladly", "boldly", "neatly", "firmly",
                "gently", "roughly", "warmly", "carefully", "suddenly", "eagerly", "happily", "proudly",
                "kindly", "politely", "bravely", "wisely", "softly", "loudly", "sternly", "sharply",
                "smoothly", "swiftly", "tightly", "loosely", "plainly", "freely", "briskly", "promptly",
                "silently", "patiently", "coolly", "keenly", "deftly", "nimbly", "steadily", "bluntly",
                "crisply", "fondly", "warily", "meekly", "gruffly", "tidily", "snugly", "evenly",
                "squarely", "grimly", "sagely", "aptly", "curtly", "tersely", "dryly", "wryly",
                "primly", "tautly", "lithely", "brightly", "stoutly", "gamely", "blithely", "jauntily",
            ),
            listOf(
                "and", "but", "so", "yet", "then", "while", "because", "though",
            ),
        ),
    )

    val russian = Grammar(
        openers = listOf("мой", "наш", "его", "твой", "ваш", "их", "тот", "этот", "один", "каждый", "любой", "другой", "такой", "некий", "иной", "всякий", "конечно", "наверное", "впрочем", "однако", "кажется", "видимо", "пожалуй", "возможно", "кстати", "значит", "похоже", "вероятно", "очевидно", "честно", "откровенно", "безусловно", "разумеется", "действительно", "признаться", "словом", "короче", "наоборот", "напротив", "следовательно", "вчера", "сегодня", "скоро", "тогда", "часто", "снова", "опять", "потом", "сразу", "теперь", "сначала", "позже", "наконец", "вдруг", "порой", "нынче", "недавно", "вскоре", "иногда", "обычно", "изредка", "давно", "всегда", "ныне"),
        openerKind = listOf(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
        structOf = listOf(3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0),
        structures = listOf(listOf("#0", "#1", "#3", "#0", "#2"), listOf("#0", "#1", "#3", "#0", "#2", "#4"), listOf("#0", "#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2", "#4"), listOf("#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2")),
        slots = listOf(
            listOf(
                "мой", "наш", "его", "твой", "ваш", "их", "тот", "этот",
                "один", "каждый", "любой", "другой", "такой", "некий", "иной", "всякий",
            ),
            listOf(
                "брат", "сосед", "директор", "водитель", "учитель", "доктор", "повар", "сторож",
                "механик", "гость", "начальник", "охранник", "курьер", "продавец", "парень", "сын",
                "отец", "друг", "дядя", "внук", "племянник", "кузнец", "пекарь", "портной",
                "сапожник", "столяр", "маляр", "слесарь", "электрик", "плотник", "каменщик", "пастух",
                "рыбак", "охотник", "часовщик", "матрос", "капитан", "полковник", "генерал", "министр",
                "депутат", "адвокат", "банкир", "кассир", "бухгалтер", "инженер", "писатель", "художник",
                "музыкант", "певец", "танцор", "садовник", "дворник", "ученик", "студент", "профессор",
                "архитектор", "пилот", "шофер", "токарь", "сварщик", "кровельщик", "тренер", "вратарь",
                "дедушка", "прадед", "тесть", "шурин", "крестник", "наследник", "жених", "вдовец",
                "писарь", "лекарь", "знахарь", "пахарь", "звонарь", "рыцарь", "переводчик", "стрелок",
                "разведчик", "моряк", "боцман", "штурман", "лоцман", "юнга", "атаман", "старшина",
                "сержант", "майор", "адмирал", "маршал", "комендант", "конвоир", "тюремщик", "палач",
                "гонец", "посол", "наместник", "барин", "помещик", "купец", "лавочник", "торговец",
                "ростовщик", "счетовод", "писец", "толмач", "аптекарь", "трубач", "барабанщик", "скрипач",
                "гусляр", "плясун", "весельчак", "силач", "богатырь", "удалец", "молодец", "храбрец",
                "мудрец", "гордец", "хитрец", "беглец", "гребец", "борец", "пловец", "чтец",
            ),
            listOf(
                "ключ", "стол", "дом", "документ", "план", "ответ", "вопрос", "шкаф",
                "ящик", "конверт", "чемодан", "забор", "мешок", "телефон", "ноутбук", "паспорт",
                "билет", "журнал", "словарь", "стул", "диван", "замок", "молоток", "топор",
                "гвоздь", "болт", "винт", "провод", "кабель", "фонарь", "зонт", "портфель",
                "рюкзак", "пакет", "сундук", "ларец", "сейф", "компас", "бинокль", "микроскоп",
                "прибор", "аппарат", "мотор", "двигатель", "насос", "вентилятор", "холодильник", "чайник",
                "стакан", "кувшин", "горшок", "самовар", "поднос", "дуршлаг", "совок", "веник",
                "ковш", "таз", "бидон", "термос", "графин", "сосуд", "пенал", "брусок",
                "стержень", "карандаш", "маркер", "циркуль", "транспортир", "ластик", "блокнот", "дневник",
                "альбом", "плакат", "свиток", "жетон", "бумажник", "ремень", "галстук", "шарф",
                "платок", "башмак", "сапог", "ботинок", "валенок", "тапок", "носок", "халат",
                "пиджак", "свитер", "картуз", "колпак", "шлем", "щит", "меч", "кинжал",
                "клинок", "штатив", "арбалет", "самокат", "велосипед", "мопед", "прицеп", "якорь",
                "штурвал", "руль", "поршень", "клапан", "рычаг", "маховик", "подшипник", "шуруп",
                "дюбель", "шпунт", "обруч", "бочонок", "черпак", "половник", "противень", "чугунок",
                "котелок", "ухват", "рубанок", "напильник", "резец", "зубец", "крючок", "лоскут",
            ),
            listOf(
                "взял", "отдал", "продал", "купил", "закрыл", "открыл", "оставил", "забрал",
                "вернул", "спрятал", "достал", "убрал", "поднял", "опустил", "сломал", "помыл",
                "вымыл", "покрасил", "подписал", "сложил", "порвал", "склеил", "собрал", "разобрал",
                "проверил", "заметил", "потерял", "получил", "отправил", "поймал", "бросил", "кинул",
                "схватил", "толкнул", "подвинул", "завязал", "развязал", "запер", "погрузил", "наполнил",
                "измерил", "взвесил", "посчитал", "пересчитал", "отметил", "пометил", "завернул", "распаковал",
                "упаковал", "нарисовал", "вычистил", "почистил", "отмыл", "разбил", "починил", "настроил",
                "передвинул", "припрятал", "стащил", "утащил", "сдвинул", "приподнял", "подобрал", "выбрал",
                "показал", "держал", "хранил", "поставил", "повернул", "предложил", "описал", "упомянул",
                "запомнил", "осмотрел", "похвалил", "испытал", "оценил", "изучил", "скопировал", "начертил",
                "напечатал", "переставил", "заполнил", "опечатал", "обвязал", "связал", "перевязал", "подвязал",
                "прицепил", "зацепил", "отцепил", "приклеил", "прибил", "привинтил", "прикрутил", "отвинтил",
                "открутил", "заклепал", "запаял", "спаял", "залудил", "смахнул", "стряхнул", "обмахнул",
                "расчистил", "намотал", "размотал", "смотал", "перемотал", "закатал", "раскатал", "свернул",
                "прижал", "отложил", "ощупал", "придвинул", "отодвинул", "пододвинул", "схоронил", "припас",
                "нащупал", "нашарил", "ухватил", "стиснул", "сжал", "разжал", "катнул", "пихнул",
                "подхватил", "перехватил", "обхватил", "захватил", "отхватил", "взвалил", "свалил", "навалил",
                "скатил", "закатил", "выкатил", "вкатил", "подкатил", "откатил", "натянул", "подтянул",
                "затянул", "оттянул", "вытянул", "протянул", "растянул", "стянул", "воткнул", "заткнул",
                "привязал", "отвязал", "навязал", "увязал", "скрепил", "укрепил", "закрепил", "прикрепил",
                "открепил", "подпилил", "отпилил", "распилил", "спилил", "просверлил", "высверлил", "пробил",
                "забил", "вбил", "подбил", "отбил", "сбил", "приколотил", "заколотил", "сколотил",
                "подклеил", "заклеил", "расклеил", "переклеил", "обклеил", "завинтил", "подвинтил", "свинтил",
                "разложил", "переложил", "подложил", "заложил", "выложил", "наложил", "уложил", "подцепил",
                "нацепил", "сцепил", "расцепил", "примерил", "отмерил", "вымерил", "замерил", "подсчитал",
                "насчитал", "отсчитал", "просчитал", "подровнял", "разровнял", "заровнял", "подчистил", "перечистил",
                "надраил", "отдраил", "продраил", "приладил", "наладил", "приспособил", "примотал", "подмотал",
                "обмотал", "замотал", "подкрутил", "накрутил", "закрутил", "перекрутил", "скрутил", "раскрутил",
                "подсунул", "засунул", "всунул", "высунул", "просунул", "рассовал", "распихал", "затолкал",
                "протолкал", "запихал", "впихнул", "отпихнул", "распрямил", "выпрямил", "погнул", "согнул",
                "разогнул", "перегнул", "надломил", "разломил", "переломил", "отломил", "подломил", "заломил",
                "наклеил", "вклеил", "отклеил", "вставил", "выставил", "приставил", "подставил", "выдвинул",
            ),
            listOf(
                "тихо", "быстро", "медленно", "спокойно", "охотно", "смело", "аккуратно", "крепко",
                "бережно", "грубо", "тепло", "осторожно", "внезапно", "радостно", "гордо", "вежливо",
                "храбро", "мудро", "мягко", "громко", "строго", "резко", "плавно", "ловко",
                "молча", "нарочно", "случайно", "дважды", "вместе", "отдельно", "рано", "поздно",
                "вчера", "утром", "ночью", "поутру", "недавно", "немедленно", "поспешно", "терпеливо",
                "ровно", "прямо", "косо", "бойко", "шустро", "цепко", "живо", "чинно",
                "смирно", "робко", "дерзко", "угрюмо", "хмуро", "весело", "бодро", "вяло",
                "тускло", "скупо", "щедро", "редко", "густо", "спешно", "тщательно", "ретиво",
            ),
            listOf(
                "и", "но", "а", "затем", "потом", "пока", "когда", "поэтому",
            ),
        ),
    )


    val german = Grammar(
        openers = listOf("die", "meine", "deine", "seine", "ihre", "unsere", "diese", "alle", "ehrlich", "offenbar", "sicher", "klar", "freilich", "allerdings", "immerhin", "wirklich", "vermutlich", "angeblich", "bekanntlich", "erstaunlich", "heute", "gestern", "damals", "danach", "bald", "oft", "endlich", "wieder", "neulich", "zuletzt", "inzwischen", "seitdem"),
        openerKind = listOf(2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
        structOf = listOf(3, 4, 5, 3, 4, 5, 3, 4, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2),
        structures = listOf(listOf("#3", "#0", "#1", "#0", "#2"), listOf("#3", "#0", "#1", "#0", "#2", "#4"), listOf("#3", "#0", "#1", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2", "#4"), listOf("#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2")),
        slots = listOf(
            listOf(
                "die", "meine", "deine", "seine", "ihre", "unsere", "diese", "alle",
            ),
            listOf(
                "Lehrer", "Fahrer", "Maler", "Richter", "Freunde", "Nachbarn", "Studenten", "Fischer", "Kollegen", "Boten", "Diener", "Reiter", "Sieger", "Helden", "Riesen", "Piraten", "Ritter", "Priester", "Meister", "Weber", "Hirten", "Schneider", "Zeugen", "Erben", "Neffen", "Enkel", "Paten", "Kunden", "Wanderer", "Trainer", "Forscher", "Dichter",
            ),
            listOf(
                "Tische", "Fenster", "Wege", "Bilder", "Rahmen", "Uhren", "Ringe", "Ketten", "Karten", "Briefe", "Zettel", "Hefte", "Stifte", "Federn", "Seile", "Netze", "Beutel", "Taschen", "Koffer", "Rohre", "Wagen", "Boote", "Segel", "Anker", "Ruder", "Leitern", "Stufen", "Balken", "Bretter", "Schrauben", "Zangen", "Schaufeln", "Harken", "Karren", "Scheunen", "Zelte", "Tunnel", "Gruben", "Brunnen", "Teiche", "Seen", "Berge", "Felder", "Wiesen", "Zweige", "Wurzeln", "Blumen", "Beeren", "Samen", "Steine", "Felsen", "Ziegel", "Fliesen", "Platten", "Scheiben", "Klingen", "Schilde", "Speere", "Pfeile", "Trommeln", "Geigen", "Harfen", "Glocken", "Riegel",
            ),
            listOf(
                "kauften", "verkauften", "holten", "machten", "legten", "stellten", "setzten", "packten", "suchten", "zeigten", "sammelten", "ordneten", "putzten", "malten", "zeichneten", "deckten", "leerten", "wechselten", "tauschten", "teilten", "sortierten", "zahlten", "bezahlten", "kochten", "reinigten", "trockneten", "formten", "bauten", "planten", "bestellten", "lieferten", "lagerten", "stapelten", "verteilten", "markierten", "notierten", "kopierten", "druckten", "falteten", "klebten", "sicherten", "testeten", "reichten", "buchten", "mieteten", "schenkten", "borgten", "sparten", "bewachten", "bewegten", "drehten", "wendeten", "kippten", "rollten", "schleppten", "zerrten", "senkten", "sperrten", "bemalten", "benutzten", "brauchten", "kannten", "nannten", "sendeten",
            ),
            listOf(
                "oft", "gern", "kaum", "bald", "immer", "wieder", "endlich", "langsam", "schnell", "leise", "ruhig", "sorgsam", "sofort", "erneut", "gerade", "zusammen",
            ),
            listOf(
                "und", "aber", "denn", "sondern",
            ),
        ),
    )

    val chinese = Grammar(
        openers = listOf("这些", "那些", "一些", "某些", "所有", "全部", "各种", "不少", "大量", "少数", "多数", "我的", "你的", "他的", "她的", "众多", "今天", "昨天", "前天", "最近", "刚才", "后来", "当时", "起初", "其实", "显然", "确实", "当然", "也许", "大概", "果然", "据说"),
        openerKind = listOf(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        structOf = listOf(3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0),
        structures = listOf(listOf("#0", "#1", "#3", "#0", "#2"), listOf("#0", "#1", "#4", "#3", "#0", "#2"), listOf("#0", "#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2"), listOf("#1", "#4", "#3", "#0", "#2"), listOf("#1", "#3", "#0", "#2", "#5", "#0", "#1", "#3", "#0", "#2")),
        slots = listOf(
            listOf(
                "这些", "那些", "一些", "某些", "所有", "全部", "各种", "不少",
                "大量", "少数", "多数", "我的", "你的", "他的", "她的", "众多",
            ),
            listOf(
                "学生", "老师", "医生", "护士", "工人", "农民", "司机", "记者",
                "律师", "演员", "歌手", "画家", "作家", "厨师", "木匠", "铁匠",
                "邻居", "朋友", "同事", "同学", "客人", "房东", "房客", "店员",
                "老板", "员工", "顾客", "读者", "观众", "听众", "游客", "旅客",
                "村民", "居民", "市民", "孩子", "青年", "老人", "姐妹", "兄弟",
                "父母", "亲戚", "助手", "专家", "学者", "教授", "校长", "班长",
                "组长", "教练", "导游", "翻译", "编辑", "作者", "商人", "农夫",
                "渔民", "猎人", "裁缝", "鞋匠", "徒弟", "师傅", "保姆", "主人",
            ),
            listOf(
                "书本", "报纸", "杂志", "信件", "包裹", "箱子", "盒子", "袋子",
                "杯子", "盘子", "勺子", "桌子", "椅子", "板凳", "沙发", "柜子",
                "抽屉", "窗帘", "地毯", "台灯", "钟表", "手表", "眼镜", "帽子",
                "鞋子", "袜子", "衣服", "裤子", "外套", "围巾", "手套", "雨伞",
                "钥匙", "绳子", "布料", "纸张", "铅笔", "钢笔", "墨水", "本子",
                "文件", "资料", "照片", "画册", "地图", "车票", "船票", "名片",
                "账单", "收据", "表格", "邮票", "硬币", "木板", "铁丝", "螺丝",
                "工具", "梯子", "水桶", "花盆", "镜子", "抹布", "尺子", "篮子",
            ),
            listOf(
                "购买", "出售", "准备", "整理", "收拾", "检查", "记录", "保存",
                "修理", "清洗", "搬运", "携带", "展示", "摆放", "收集", "挑选",
                "更换", "归还", "借用", "使用", "制作", "包装", "运送", "分配",
                "处理", "保管", "寻找", "发现", "取回", "送来", "带走", "放下",
                "清点", "核对", "登记", "编号", "标记", "复印", "装订", "缝补",
                "铺开", "折叠", "悬挂", "张贴", "涂抹", "擦拭", "冲洗", "晾晒",
                "测量", "计算", "分类", "排列", "堆放", "卸下", "拆开", "组装",
                "调换", "补充", "领取", "缴纳", "租用", "定制", "采购", "交付",
            ),
            listOf(
                "立刻", "马上", "慢慢", "认真", "仔细", "经常", "偶尔", "已经",
                "终于", "反复", "顺利", "悄悄", "迅速", "逐渐", "特意", "临时",
            ),
            listOf(
                "而且", "但是", "然后", "因此",
            ),
        ),
    )

    val persian = Grammar(
        openers = listOf("راستش", "خوشبختانه", "متاسفانه", "ظاهرا", "مسلما", "احتمالا", "طبیعتا", "واقعا", "یقینا", "اصولا", "عملا", "ضمنا", "اتفاقا", "معمولا", "تقریبا", "حتما", "قطعا", "البته", "درواقع", "خلاصه", "بنابراین", "درنتیجه", "همچنین", "وانگهی", "اساسا", "نهایتا", "دقیقا", "عمدتا", "غالبا", "اکثرا", "عموما", "صرفا", "دیروز", "امروز", "فردا", "دیشب", "امشب", "صبح", "ظهر", "عصر", "شب", "بعد", "سپس", "قبلا", "اخیرا", "همیشه", "گاهی", "اغلب", "دوباره", "سرانجام", "ناگهان", "فورا", "بلافاصله", "همزمان", "آنگاه", "امروزه", "الان", "اکنون", "اینجا", "آنجا", "همانجا", "بیرون", "پارسال", "امسال"),
        openerKind = listOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
        structOf = listOf(0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0),
        structures = listOf(listOf("#1", "#0", "#2", "را", "#3"), listOf("#1", "#0", "#2", "را", "#4", "#3"), listOf("#1", "#0", "#2", "را", "#3", "#5", "#1", "#0", "#2", "را", "#3")),
        slots = listOf(
            listOf(
                "این", "آن", "همین", "همان", "هر", "یک", "دو", "سه",
                "چهار", "پنج", "شش", "هفت", "هشت", "ده", "دوازده", "چند",
            ),
            listOf(
                "مدیر", "برادر", "خواهر", "همسایه", "راننده", "معلم", "دکتر", "پرستار",
                "مهندس", "نویسنده", "نقاش", "خواننده", "بازیگر", "کارگر", "کشاورز", "باغبان",
                "نجار", "آشپز", "نانوا", "فروشنده", "خریدار", "مسافر", "راهنما", "مترجم",
                "منشی", "حسابدار", "وکیل", "داور", "مربی", "ورزشکار", "دانشجو", "استاد",
                "پزشک", "داروساز", "خلبان", "ملوان", "ماهیگیر", "چوپان", "دامپزشک", "آرایشگر",
                "خیاط", "کفاش", "عکاس", "خبرنگار", "ناشر", "شاعر", "نوازنده", "بازرس",
                "نگهبان", "پیشخدمت", "میزبان", "مهمان", "همکار", "همسر", "پدربزرگ", "مادربزرگ",
                "عمو", "دایی", "خاله", "عمه", "پستچی", "راهب", "صاحبخانه", "شاگرد",
            ),
            listOf(
                "جعبه", "نامه", "پنجره", "میز", "صندلی", "نردبان", "سبد", "بطری",
                "شمع", "آینه", "مداد", "بلیت", "کیف", "پتو", "بالش", "کتری",
                "قوری", "نعلبکی", "چکش", "لنگر", "دوربین", "کشو", "کمد", "بسته",
                "پوشه", "روبان", "دکمه", "جیب", "یقه", "بشکه", "سطل", "بیل",
                "فانوس", "دستمال", "ماژیک", "اسفنج", "جام", "آهنربا", "پرچم", "سوت",
                "آچار", "سوزن", "نخ", "پاکت", "دفتر", "چتر", "چمدان", "کوله",
                "دستکش", "شال", "کلاه", "حوله", "پرده", "قالی", "تشک", "پارچ",
                "لیوان", "بشقاب", "کاسه", "قاشق", "چنگال", "سینی", "ملاقه", "قیف",
                "رنده", "ماهیتابه", "دیگ", "قوطی", "چرخ", "دسته", "پتک", "تبر",
                "داس", "ماله", "ناودان", "لولا", "گیره", "اهرم", "قرقره", "سوپاپ",
                "پیستون", "منگنه", "پرونده", "دفترچه", "رسید", "تقویم", "پوستر", "آلبوم",
                "پالت", "جامدادی", "کیسه", "صندوق", "کارتن", "پارچه", "شیشه", "بادکنک",
                "بادبزن", "ساعت", "زنگ", "عقربه", "درجه", "حسگر", "کلید", "پریز",
                "دوشاخه", "سیم", "طناب", "زنجیر", "بند", "سگک", "زیپ", "قلاب",
                "میخ", "پیچ", "مهره", "فنر", "انبر", "دیلم", "کلنگ", "اره",
                "مته", "سنباده", "آجر", "کاشی", "تخته", "الوار", "میله", "واشر",
            ),
            listOf(
                "برداشت", "گرفت", "دید", "خرید", "فروخت", "آورد", "برد", "گذاشت",
                "شکست", "بست", "شست", "خواند", "نوشت", "ساخت", "یافت", "فرستاد",
                "کشید", "انداخت", "چید", "دوخت", "پخت", "کاشت", "شمرد", "سنجید",
                "پوشاند", "تراشید", "بافت", "برید", "رساند", "پیچید", "مالید", "فشرد",
                "کوبید", "ریخت", "نوشید", "جوید", "بلعید", "پیمود", "قاپید", "خواست",
                "آموخت", "سپرد", "بخشید", "پسندید", "چشید", "پوشید", "شکافت", "دوشید",
                "گشود", "نهاد", "افکند", "آویخت", "سرود", "پرداخت", "انباشت", "چسباند",
                "سوزاند", "شناخت", "گذراند", "لرزاند", "چرخاند", "داد", "پذیرفت", "پاشید",
            ),
            listOf(
                "آهسته", "تند", "آرام", "دقیق", "کامل", "سریع", "محکم", "نرم",
                "خوب", "زود", "دیر", "یواش", "تمیز", "مرتب", "راحت", "سخت",
            ),
            listOf(
                "و", "اما", "ولی", "پس",
            ),
        ),
    )
}
